### ISSUE TITLE
cannot host the server

### ISSUE THREAD

**Issue by retroname** [nuke-ops/Nostra-13#250]
so, this error appears when I try to host the code in a vps, can you help?
[message.txt](https://github.com/nuke-ops/Nostra-13/files/7945585/message.txt)

**Comment by maksxpl** [comment]
I guess you're hosting on linux, if so you can, just pm me on discord (maksxpl#8503) or go to our discord(https://discord.gg/bxgeRPq) and ping me or just say about your problem on #coderbus

Generally I'd recommend to go on Discord with stuff like this (because it's not a bug), you'd get faster response. 

tldr; I'm not sure what's exactly wrong but I guess you just need to compile auxmos on your machine, if so,
download the https://github.com/Putnam3145/auxmos and copy entire `auxmos/` into Nostra folder
